name: Create and publish Docker image

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*'
    pull_request:
        branches:
            - 'main'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: matt1432/eiskaltdcpp-docker

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            # Uses the `docker/login-action` action to log in to the Container registry
            # registry using the account and password that will publish the packages.
            # Once published, the packages are scoped to the account defined here.
            - name: Log in to the Container registry
              uses: docker/login-action@v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # https://github.com/docker/metadata-action#about
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v6
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}

            # https://github.com/docker/build-push-action#usage
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v7
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            # [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v4
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-registry: true
